# Generated by Django 3.0.4 on 2020-03-25 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DietProgram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dietProgram_name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=1000)),
                ('dietProgram_logo', models.CharField(max_length=1000)),
            ],
        ),
    ]
