# Generated by Django 3.0.4 on 2020-04-11 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('foodlist', '0004_auto_20200325_1345'),
        ('customer', '0002_customer_customer_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerBag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Customer')),
                ('foodlist', models.ManyToManyField(to='foodlist.FoodList')),
            ],
        ),
    ]
