# Generated by Django 3.0.4 on 2020-04-12 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodlist', '0004_auto_20200325_1345'),
        ('customerbag', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerbag',
            name='foodlist',
        ),
        migrations.AddField(
            model_name='customerbag',
            name='foodlist',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='foodlist.FoodList'),
            preserve_default=False,
        ),
    ]
