# Generated by Django 3.0.4 on 2020-04-12 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerbag', '0002_auto_20200412_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerbag',
            name='total_price',
            field=models.PositiveIntegerField(default=3),
            preserve_default=False,
        ),
    ]
