# Generated by Django 3.0.4 on 2020-04-13 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customerbag', '0004_customerbag_is_purchased'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerbag',
            name='is_purchased',
        ),
    ]
