# Generated by Django 3.0.4 on 2020-03-25 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dietprogram', '0001_initial'),
        ('vendor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foodlist_name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=1000)),
                ('foodlist_logo', models.CharField(max_length=1000)),
                ('available_date', models.DateField(blank=True, null=True)),
                ('diet_program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dietprogram.DietProgram')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendor.Food')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendor.Vendor')),
            ],
        ),
    ]
