# Generated by Django 3.0.4 on 2020-03-25 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor', '0001_initial'),
        ('foodlist', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodlist',
            name='food',
        ),
        migrations.AddField(
            model_name='foodlist',
            name='food',
            field=models.ManyToManyField(to='vendor.Food'),
        ),
    ]
