# Generated by Django 3.0.4 on 2020-03-25 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodlist', '0002_auto_20200325_1326'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foodlist',
            old_name='food',
            new_name='foods',
        ),
    ]
