# Generated by Django 3.0.4 on 2020-03-25 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
        ('foodlist', '0003_auto_20200325_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodlist',
            name='foods',
            field=models.ManyToManyField(to='food.Food'),
        ),
    ]
