# Generated by Django 3.0.4 on 2020-04-12 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodlist', '0004_auto_20200325_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodlist',
            name='price',
            field=models.PositiveIntegerField(default=3),
            preserve_default=False,
        ),
    ]
