# Generated by Django 3.0.4 on 2020-04-16 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_customeraddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.CustomerAddress'),
        ),
    ]
