# Generated by Django 3.0.4 on 2020-04-16 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_auto_20200416_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_location',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.CustomerAddress'),
        ),
    ]
