# Generated by Django 3.0.4 on 2020-04-16 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_auto_20200416_1452'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='customer_location',
        ),
        migrations.DeleteModel(
            name='CustomerAddress',
        ),
    ]
