# Generated by Django 3.0.4 on 2020-04-17 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0012_auto_20200417_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_phone',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
