# Generated by Django 3.0.4 on 2020-04-17 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0013_auto_20200417_1914'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='customer_phone',
        ),
    ]
