# Generated by Django 3.0.4 on 2020-04-17 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0015_customer_customer_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_phone',
            field=models.CharField(blank=True, default=3, max_length=100),
            preserve_default=False,
        ),
    ]
