# Generated by Django 3.0.4 on 2020-04-13 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderitem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='order_id',
            field=models.PositiveIntegerField(default=2),
            preserve_default=False,
        ),
    ]
