# Generated by Django 3.0.4 on 2020-04-16 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeraddress',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='customeraddress',
            name='postal_code',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='customeraddress',
            name='street',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
