# Generated by Django 3.0.4 on 2020-04-17 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0002_auto_20200416_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeraddress',
            name='province',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='vendoraddress',
            name='province',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
