# Generated by Django 3.0.4 on 2020-05-02 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0003_auto_20200417_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeraddress',
            name='postal_code',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
