# Generated by Django 3.0.4 on 2020-05-02 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0004_auto_20200502_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeraddress',
            name='postal_code',
            field=models.CharField(blank=True, default=3, max_length=100),
            preserve_default=False,
        ),
    ]
