# Generated by Django 3.0.4 on 2020-05-02 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0005_auto_20200502_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeraddress',
            name='postal_code',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
