# Generated by Django 3.0.4 on 2020-05-02 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0006_auto_20200502_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendoraddress',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='vendoraddress',
            name='postal_code',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='vendoraddress',
            name='street',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
