# Generated by Django 3.0.4 on 2020-04-12 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerbag', '0003_customerbag_total_price'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='CustomerBag',
        ),
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(to='customerbag.CustomerBag'),
        ),
    ]
