# Generated by Django 3.0.4 on 2020-04-13 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderitem', '0002_orderitem_order_id'),
        ('order', '0006_delete_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='item',
            field=models.ManyToManyField(to='orderitem.OrderItem'),
        ),
    ]
